#!/bin/bash

#rake db:create
#rake db:migrate

#bundle exec rake db:test:prepare

#rerun --background 'bundle exec rackup --host 0.0.0.0 -p 3000'

bundle exec rake db:setup
bundle exec rake db:seed
bundle install
bundle exec rerun --background 'rails server -b 0.0.0.0 -p 3000'
