require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe Api::V1::WalkingsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Walking. As you add validations to Walking, be sure to
  # adjust the attributes here as well.

  let(:client) { create(:client) }
  let(:dogs) { 2.times.map { create(:dog, client: client) }}
  let(:valid_attributes) do
    attrs = build(:walking).attributes
    attrs.merge!(dog_ids: dogs.map(&:to_param))

    attrs.delete("id")
    attrs.delete("created_at")
    attrs.delete("updated_at")

    attrs
  end

  let(:invalid_attributes) {
    { lon: '' }
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # WalkingsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "returns a success response" do
      Walking.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(response).to be_successful
    end

    it "returns upcoming walkings" do
      5.times do
        create(:walking, :upcomming)
      end

      5.times do
        create(:walking, :outdated)
      end

      get :index, params: { upcoming: true  }, session: valid_session
      expect(JSON.parse(response.body).size).to eql(5)
    end

    it "returns all walkings" do
      5.times do
        create(:walking, :upcomming)
      end

      5.times do
        create(:walking, :outdated)
      end

      get :index, params: {}, session: valid_session
      expect(JSON.parse(response.body).size).to eql(10)
    end
  end

  describe "GET #show" do
    it "returns a success response" do
      walking = Walking.create! valid_attributes
      get :show, params: {id: walking.to_param}, session: valid_session
      expect(response).to be_successful
    end

    it 'returns the begin and end time' do
      time = Time.now

      walking = create(:walking, :with_dogs, schedule_time: time)
      walking.short_time!

      get :show, params: {id: walking.to_param}, session: valid_session

      parsed_response = JSON.parse(response.body)
      schedule_time = DateTime.parse(parsed_response['schedule_time']).utc
      end_time = DateTime.parse(parsed_response['end_time']).utc

      expect(schedule_time).to eql(walking.schedule_time.utc)
      expect(end_time).to eql(walking.end_time.utc)
    end

    it 'returns the price for walking' do
      walking = create(:walking, :with_two_dogs, :short_time)

      get :show, params: {id: walking.to_param}, session: valid_session

      parsed_response = JSON.parse(response.body)
      expect(parsed_response['price']).to eql(40)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Walking" do
        expect {
          post :create, params: {walking: valid_attributes}, session: valid_session
        }.to change(Walking, :count).by(1)
      end

      it "renders a JSON response with the new walking" do

        post :create, params: {walking: valid_attributes}, session: valid_session
        expect(response).to have_http_status(:created)
        expect(response.content_type).to eq('application/json')
        expect(response.location).to eq(api_v1_walking_url(Walking.last))
      end
    end

    context "with invalid params" do
      it "renders a JSON response with errors for the new walking" do

        post :create, params: {walking: invalid_attributes}, session: valid_session
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq('application/json')
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        { lon: '2' }
      }

      it "updates the requested walking" do
        walking = Walking.create! valid_attributes
        put :update, params: {id: walking.to_param, walking: new_attributes}, session: valid_session
        walking.reload
      end

      it "renders a JSON response with the walking" do
        walking = Walking.create! valid_attributes

        put :update, params: {id: walking.to_param, walking: valid_attributes}, session: valid_session
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to eq('application/json')
      end
    end

    context "with invalid params" do
      it "renders a JSON response with errors for the walking" do
        walking = Walking.create! valid_attributes

        put :update, params: {id: walking.to_param, walking: invalid_attributes}, session: valid_session
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq('application/json')
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested walking" do
      walking = Walking.create! valid_attributes
      expect {
        delete :destroy, params: {id: walking.to_param}, session: valid_session
      }.to change(Walking, :count).by(-1)
    end
  end

end
